# -*- coding: utf-8 -*-
"""
Created on Fri Dec 30 15:13:45 2022

@author: Arnav

DESCRIPTION:
Plots the data generated by csvToWindRose.py for a
visual representation of the raw wind data.
"""

from floris.tools import FlorisInterface, WindRose, wind_rose

windRoseFile = "WIND_ROSE.csv"

# Read the wind data
wind_rose = WindRose()
wind_rose.read_wind_rose_csv(windRoseFile)

# Plot the wind rose
wind_rose.plot_wind_rose()